export const membershipTerms = [
   'Legal age to join the center is 16 years and above under 50 years.',
   'You must respect and observe the customs and traditions of the Kingdom of Saudi Arabia.',
   'Smoking is strictly forbidden inside the center, as well as prevent foods and beverages.',
   'Exercise prevents practicing without sports dress in full and full body swim wear and without wearing a suitable athletic shoe.',
   'Must apply the instructions for water areas (Swimming Pool/ Jacuzzi Sauna / Steam).',
   'private ownership clothes cabinets SIMS are considered within hours she was at the club, and the right to manage emptying the contents of the lockers at the end of the official working hours without incurring any responsibility.',
   'It is strictly forbidden to throw weights on the ground in iron lounge, and also must re-weights and tools into place after use in the lounge and a fitness iron.',
   'Must deal with all the devices with care, joint and is fully responsible for any damage to any device located in the result of misuse.',
   'Money is non refundable but subscription may be waived after approval by the administration under waived terms.',
   "Verbal or physical assault on any of the Centre's staff is subject to unsubscribe, and in the case of any complaint by the participants with respect to any employee can file a complaint through the center's management.",
   'It is strictly forbidden the introduction of hormones and steroids different kinds to the center, but coaches are not allowed to sell nutritional supplements such as proteins and other hormones or steroids such as, among others.',
   'Not allowed to give the coaches a joint staff of the center or any sums of money or in-kind gifts, and assume joint responsibility alone pay any sums of money and is not entitled to claim the company financially.',
   'Must be reported to the coach in case of any health problems before physical activity.',
   'The company does not assume any responsibility relating to the occurrence of any injuries subscriber God forbid, or any of the common loss of personal belongings.',
   'In case of pregnancy, the company does not assume any responsibility toward the subscriber, membership cannot be postponement.',
   'The Company reserves the right to shut down the center or any of its facilities for the purposes of periodic maintenance and cleaning without prior notice.',
   'The company has the right to unsubscribe to any subscriber if offended behavior or set up a disturbance of subscribers did not adhere to the instructions of the center and the laws of any amounts without reply financially.',
   'The company has the right to cancel the subscription of any participant if she does not comply with the precautionary measures.',
   'Have the right to stop the joint participation according to the quality subscription.',
   "On the common commitment of all the company's written instructions to this application as well as the instructions on the internal boards center and administrative circulars issued may advance the company.",
   'Taking photos is prohibited strictly, the management has the right to unsubscribe the subscriber without reply financially.',
   'You must comply with the start date recorded on the invoice.',
 ];
 